### ISSUE TITLE
하드코딩..보다는 application.properties 이용하세요!

### ISSUE THREAD

**Issue by nhn-academy-marco** [nhn-on7/marketgg-client#18]
https://github.com/nhn-on7/marketgg-client/blob/45f80111f4efb4f667f34e014df0c212c01100ba/src/main/java/com/nhnacademy/marketgg/client/config/WebConfiguration.java#L21-L24

 - application.properties --> profile 분리 ( 서버환경(배포된 서버환경),  로컬환경 )
 - gateway 서버주소는 ->  application.properties 쪽에서 관리하는게 좋을거 같아요

**Comment by psw4887** [comment]
@corock 저희 아직 properties로 관리되는것 같던데 client는 yml 사용안하나요?

**Comment by corock** [comment]
점심먹고 올려놓을게요

**Comment by psw4887** [comment]
하핫 해주시는김에 Bean도 yml에 빼주시죠
